# Data Consumption — Delta Lake discovery

Discover and inspect Delta tables synced from each pipeline zone’s `metadata/observations.parquet`:

| Zone | Bucket (default) | Delta path |
|------|------------------|------------|
| landing | `landing-zone` | `metadata/observations_delta/` |
| trusted | `trusted-zone` | `metadata/observations_delta/` |
| exploitation | `exploitation-zone` | `metadata/observations_delta/` |

Requires MinIO (`docker compose up -d minio`) and at least one zone processing run that completed Delta sync.

## Paths and environment

In [7]:
from pathlib import Path
import os
import sys

_here = Path.cwd().resolve()
_root = None
for p in [_here, *_here.parents]:
    if (p / "shared" / "minio_helpers.py").is_file():
        _root = p
        break
if _root is None:
    raise RuntimeError("Repo root not found — open the notebook from the BDM-Cymatics tree")

PROJECT_ROOT = str(_root)
DATA_CONSUMPTION_DIR = _root / "data_consumption"

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)
if str(DATA_CONSUMPTION_DIR) not in sys.path:
    sys.path.insert(1, str(DATA_CONSUMPTION_DIR))

from dotenv import load_dotenv
load_dotenv(_root / ".env", override=False)

print("PROJECT_ROOT =", PROJECT_ROOT)
print("MINIO_ENDPOINT =", os.environ.get("MINIO_ENDPOINT", "localhost:9000"))

PROJECT_ROOT = /Users/arman/Desktop/2026-sprinrg/BDM/Cymatics/BDM-Cymatics
MINIO_ENDPOINT = localhost:9000

## Zone table registry

In [8]:
from shared.minio_helpers import LANDING_ZONE_BUCKET, MINIO_ENDPOINT, create_minio_client
from shared.sync_delta import OBSERVATIONS_DELTA_PATH, s3_storage_options

STORAGE_OPTIONS = s3_storage_options()

ZONE_TABLES = {
    "landing": {
        "bucket": LANDING_ZONE_BUCKET,
        "delta_path": OBSERVATIONS_DELTA_PATH,
    },
    "trusted": {
        "bucket": os.environ.get("TRUSTED_ZONE_BUCKET", "trusted-zone"),
        "delta_path": OBSERVATIONS_DELTA_PATH,
    },
    "exploitation": {
        "bucket": os.environ.get("EXPLOITATION_ZONE_BUCKET", "exploitation-zone"),
        "delta_path": OBSERVATIONS_DELTA_PATH,
    },
}

for zone, cfg in ZONE_TABLES.items():
    uri = f"s3a://{cfg['bucket']}/{cfg['delta_path']}"
    print(f"  {zone:14} {uri}")

  landing        s3a://landing-zone/metadata/observations_delta
  trusted        s3a://trusted-zone/metadata/observations_delta
  exploitation   s3a://exploitation-zone/metadata/observations_delta

## Discover tables (row counts + schema)

In [9]:
from deltalake import DeltaTable


def delta_table_uri(bucket: str, delta_path: str = OBSERVATIONS_DELTA_PATH) -> str:
    return f"s3a://{bucket}/{delta_path}"


def minio_has_delta_log(client, bucket: str, delta_path: str = OBSERVATIONS_DELTA_PATH) -> bool:
    """Quick check: Delta transaction log present on MinIO."""
    prefix = delta_path.rstrip("/") + "/_delta_log/"
    try:
        for _ in client.list_objects(bucket, prefix=prefix, recursive=True):
            return True
    except Exception:
        return False
    return False


def inspect_delta_table(zone: str, bucket: str, delta_path: str = OBSERVATIONS_DELTA_PATH):
    """Return summary dict or error message for one zone Delta table."""
    uri = delta_table_uri(bucket, delta_path)
    client = create_minio_client()
    if not client.bucket_exists(bucket):
        return {"zone": zone, "uri": uri, "status": "missing_bucket"}
    if not minio_has_delta_log(client, bucket, delta_path):
        return {"zone": zone, "uri": uri, "status": "no_delta_table"}
    try:
        dt = DeltaTable(uri, storage_options=STORAGE_OPTIONS)
        version = dt.version()
        pdf = dt.to_pandas()
        return {
            "zone": zone,
            "uri": uri,
            "status": "ok",
            "version": version,
            "num_rows": len(pdf),
            "num_columns": len(pdf.columns),
            "columns": list(pdf.columns),
            "dataframe": pdf,
        }
    except Exception as e:
        return {"zone": zone, "uri": uri, "status": "error", "error": str(e)}


summaries = []
loaded = {}

print(f"MinIO: {MINIO_ENDPOINT}\n")
print(f"{'Zone':<14} {'Status':<16} {'Rows':>8} {'Cols':>6}  URI")
print("-" * 90)

for zone, cfg in ZONE_TABLES.items():
    info = inspect_delta_table(zone, cfg["bucket"], cfg["delta_path"])
    summaries.append(info)
    status = info["status"]
    if status == "ok":
        loaded[zone] = info["dataframe"]
        rows, cols = info["num_rows"], info["num_columns"]
        print(f"{zone:<14} {'ready':<16} {rows:>8} {cols:>6}  {info['uri']}")
    elif status == "no_delta_table":
        print(f"{zone:<14} {'no delta table':<16} {'—':>8} {'—':>6}  {info['uri']}")
    elif status == "missing_bucket":
        print(f"{zone:<14} {'bucket missing':<16} {'—':>8} {'—':>6}  {info['uri']}")
    else:
        print(f"{zone:<14} {'error':<16} {'—':>8} {'—':>6}  {info['uri']}")
        print(f"             {info.get('error', '')}")

MinIO: localhost:9000

Zone           Status               Rows   Cols  URI
------------------------------------------------------------------------------------------
landing        ready                  22     12  s3a://landing-zone/metadata/observations_delta
trusted        ready                  22     27  s3a://trusted-zone/metadata/observations_delta
exploitation   ready                  22     39  s3a://exploitation-zone/metadata/observations_delta

## Exploitation zone — sample rows

Full feature-enriched metadata (Spark + Python features). Adjust `PREVIEW_ROWS` or filter by `uuid` below.

In [4]:
import pandas as pd

PREVIEW_ROWS = 10
UUID_FILTER = ""  # optional: paste a uuid to filter, e.g. "feca5971-..."

if "exploitation" not in loaded:
    print(
        "Exploitation Delta table not available. "
        "Run exploitation_zone_processing.py first (includes Parquet → Delta sync)."
    )
else:
    exp = loaded["exploitation"]
    if UUID_FILTER.strip():
        mask = exp["uuid"].astype(str).str.contains(UUID_FILTER.strip(), case=False, na=False)
        exp = exp.loc[mask]
        print(f"Filtered to {len(exp)} row(s) matching uuid fragment {UUID_FILTER!r}")
    print(f"Total rows: {len(exp)}  |  columns: {len(exp.columns)}")
    display(exp.head(PREVIEW_ROWS))

Total rows: 22  |  columns: 39

,uuid,source_id,time_recorded/added,processing_version,duration,symmetry_score,pattern_stability_score,image_resolution,video_resolution,audio_size,...,spectral_rolloff_hz,spectral_flatness,signal_energy,spectral_entropy,zero_crossing_rate,loudness,MFCCs,harmonic_energy_ratio,feature_version,feature_processing_time(seconds)
0,00a11728-db7d-44b1-912f-1d2e4b0899c8,485373,2019-09-18T16:59:28Z,2.0.0,8.49047619047619,0.9594778915503759,0.982891766782357,2048x2048,600x600,748904,...,60.891755468311835,0.06135482609322896,31809.275793315017,5.048887909589329,0.0033490995622668116,-10.708168563387659,"[-8.494935, 13.132322, 11.240527, 8.602461, 5....",0.6862886798027035,1.0.0,0.08176316699245945
1,09bfde40-7dfb-46bd-a2bf-df18007ec9ed,627792,2022-04-12T11:24:10Z,2.0.0,4.5416780045351475,0.9581728028750407,0.9217067601527396,2048x2048,600x600,400620,...,4984.281135165362,0.18480683257430908,3351.386362538923,9.799671885171657,0.16930704439129848,-17.76430431776451,"[24.982985, 7.10206, -6.065839, 3.864542, -5.2...",0.031138259041744977,1.0.0,0.042195458998321556
2,13159abb-f78e-48a8-93fb-9157e02475d7,809062,2025-05-28T20:27:16Z,2.0.0,5.17795918367347,0.9566261626058694,0.9614030512102695,2048x2048,600x600,456740,...,7542.16064953492,0.4284869609440066,72.53867756783441,8.566126596440721,0.1050681638033344,-34.980275783483386,"[-36.634358, 7.999476, 3.494112, 1.487157, -2....",0.2379008855871889,1.0.0,0.040009958000155166
3,31dac2a1-65a2-439d-a958-3574fef224d0,34067,2007-04-22T16:01:50Z,2.0.0,9.143922902494332,0.9527764653175316,0.9432445087546428,2048x2048,600x600,806538,...,2332.0406599429134,0.062251579491353445,14302.598167373702,9.389344952163949,0.0873089875659027,-14.501562078185016,"[24.746308, 20.276136, -12.810344, 10.696835, ...",0.03664666389861531,1.0.0,0.10485495800094213
4,3bbf9f45-8666-4d97-981e-3b0cf835f5fa,700014,2023-08-22T02:28:29Z,2.0.0,2.681904761904762,0.9582991657301841,0.9555594668016012,2048x2048,600x600,236588,...,10196.484375,0.2442409093755489,384.4900325967802,9.464581531234925,0.14251168925603064,-24.87996855103284,"[-4.04829, 4.279336, -11.18562, 0.62858, -7.29...",0.044539108921317384,1.0.0,0.011293083007331006
5,3d6ab8ab-b4a3-4466-bbf4-c34380266bc9,810426,2025-06-03T13:26:43Z,2.0.0,5.748526077097505,0.960470176786176,0.9619090318165576,2048x2048,600x600,507064,...,545.5311427557098,0.03355321024388594,6548.3348792961915,4.5746025790225,0.01776268298166929,-15.878642143051454,"[-32.194956, 23.594216, 18.011861, 5.743379, -...",0.5475378417221353,1.0.0,0.025981958999182098
6,56a22272-53a9-4ad8-8729-0c0c844d08fd,56a22272-53a9-4ad8-8729-0c0c844d08fd,2026-05-19T05:49:21.212525Z,2.0.0,5.0,0.9579746621824408,0.9408064215343626,2048x2048,600x600,441044,...,3800.2000000000003,0.40218133859874794,205.12598580539202,6.582087150781228,0.07017718901219507,-30.313879125821312,"[-0.319516, 7.668603, 2.173735, 3.786509, 0.54...",0.35766522456735983,1.0.0,0.021290624994435348
7,5706b0f9-a9d9-4cd3-bbe2-668eec60d5c1,507265,2020-03-01T14:55:51Z,2.0.0,2.1714512471655327,0.9632355673172981,0.9717637580502066,2048x2048,600x600,191566,...,7675.972473136246,0.027505515727260205,1507.4810456422401,7.802720285025783,0.2006265664160401,-18.02936812381691,"[-29.63496, 5.179067, -10.030393, 12.225316, 3...",0.09399172925735319,1.0.0,0.013219207990914583
8,60d4baa2-d190-4196-afdd-51b160178e62,96146,2010-05-06T09:12:28Z,2.0.0,2.450793650793651,0.9640948551798134,0.9737635341400718,2048x2048,600x600,216204,...,3445.4145077720204,0.12907374100707514,4659.212857981815,6.773665144067635,0.10850396469249346,-13.6543278419738,"[27.958382, 4.575136, -2.414228, -2.776886, -4...",0.1827458006637903,1.0.0,0.0136905840045074
9,6eda6370-90ad-4b6e-8aa0-4971155d9975,740418,2024-06-10T15:07:37Z,2.0.0,5.421337868480726,0.9679289676490102,0.983544726814603,2048x2048,600x600,478206,...,7331.954023950042,0.2724454951767677,302.0439265190852,4.158336940311943,0.01634599297306341,-28.984749562952878,"[-43.370976, 14.089994, 9.023856, 8.096353, 2....",0.7708508131955234,1.0.0,0.03741566700045951

## Column overview (exploitation)

In [5]:
if "exploitation" in loaded:
    exp = loaded["exploitation"]
    feature_cols = [
        c
        for c in exp.columns
        if c
        in {
            "spectral_centroid_hz",
            "spectral_bandwidth_hz",
            "spectral_rolloff_hz",
            "spectral_flatness",
            "signal_energy",
            "spectral_entropy",
            "zero_crossing_rate",
            "loudness",
            "MFCCs",
            "harmonic_energy_ratio",
        }
    ]
    meta = pd.DataFrame(
        {
            "column": exp.columns,
            "dtype": [str(exp[c].dtype) for c in exp.columns],
            "non_null": [int(exp[c].notna().sum()) for c in exp.columns],
        }
    )
    display(meta)
    if feature_cols:
        print("\nDerived feature columns:", ", ".join(feature_cols))
        display(exp[feature_cols].describe().T)

                              column   dtype  non_null
0                               uuid  object        22
1                          source_id  object        22
2                time_recorded/added  object        22
3                 processing_version  object        22
4                           duration  object        22
5                     symmetry_score  object        22
6            pattern_stability_score  object        22
7                   image_resolution  object        22
8                   video_resolution  object        22
9                         audio_size  object        22
10                        image_size  object        22
11                        video_size  object        22
12          processing_time(seconds)  object        22
13                            device  object        22
14                      audio_format  object        22
15                            source  object        22
16                 peak_frequency_hz  object        22
17                       peak_time_s  object        22
18                    peak_amplitude  object        22
19                          peak_rms  object        22
20                        audio_path  object        22
21                        image_path  object        22
22                        video_path  object        22
23           all_peak_frequencies_hz  object        22
24                              tags  object        22
25                       description  object        22
26                          category  object        22
27              spectral_centroid_hz  object        22
28             spectral_bandwidth_hz  object        22
29               spectral_rolloff_hz  object        22
30                 spectral_flatness  object        22
31                     signal_energy  object        22
32                  spectral_entropy  object        22
33                zero_crossing_rate  object        22
34                          loudness  object        22
35                             MFCCs  object        22
36             harmonic_energy_ratio  object        22
37                   feature_version  object        22
38  feature_processing_time(seconds)  object        22

Derived feature columns: spectral_centroid_hz, spectral_bandwidth_hz, spectral_rolloff_hz, spectral_flatness, signal_energy, spectral_entropy, zero_crossing_rate, loudness, MFCCs, harmonic_energy_ratio

,count,unique,top,freq
spectral_centroid_hz,22,22,59.45384376663341,1
spectral_bandwidth_hz,22,22,56.52059557145536,1
spectral_rolloff_hz,22,22,60.891755468311835,1
spectral_flatness,22,22,0.06135482609322896,1
signal_energy,22,22,31809.275793315017,1
spectral_entropy,22,22,5.048887909589329,1
zero_crossing_rate,22,22,0.0033490995622668116,1
loudness,22,22,-10.708168563387659,1
MFCCs,22,22,"[-8.494935, 13.132322, 11.240527, 8.602461, 5....",1
harmonic_energy_ratio,22,22,0.6862886798027035,1

## Compare zones (uuid overlap)

Shows how many UUIDs appear in each zone’s Delta table (pipeline should grow landing → trusted → exploitation).

In [6]:
if not loaded:
    print("No Delta tables loaded — run zone processing + sync first.")
else:
    uuid_sets = {
        zone: set(df["uuid"].astype(str).str.strip())
        for zone, df in loaded.items()
        if "uuid" in df.columns
    }
    for zone, uuids in uuid_sets.items():
        print(f"  {zone}: {len(uuids)} uuid(s)")
    if len(uuid_sets) >= 2:
        zones = list(uuid_sets.keys())
        for i, a in enumerate(zones):
            for b in zones[i + 1 :]:
                inter = uuid_sets[a] & uuid_sets[b]
                print(f"  {a} ∩ {b}: {len(inter)} shared uuid(s)")

  landing: 22 uuid(s)
  trusted: 22 uuid(s)
  exploitation: 22 uuid(s)
  landing ∩ trusted: 22 shared uuid(s)
  landing ∩ exploitation: 22 shared uuid(s)
  trusted ∩ exploitation: 22 shared uuid(s)

## Optional — other zones preview

In [ ]:
ZONE_PREVIEW = "landing"  # landing | trusted | exploitation
N = 5

if ZONE_PREVIEW not in loaded:
    print(f"No data for zone {ZONE_PREVIEW!r}.")
else:
    df = loaded[ZONE_PREVIEW]
    cols = [c for c in ["uuid", "source", "peak_frequency_hz", "audio_path"] if c in df.columns]
    display(df[cols].head(N) if cols else df.head(N))